sudo: required
services:
  - docker
before_install:
  - docker build -t stfdmv/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run stfdmv/react-test npm test -- --coverage
after_success:
  - docker build -t stfdmv/multi-client ./client
  - docker build -t stfdmv/multi-nginx ./nginx
  - docker build -t stfdmv/multi-server ./server
  - docker build -t stfdmv/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stfdmv/multi-client
  - docker push stfdmv/multi-nginx
  - docker push stfdmv/multi-server
  - docker push stfdmv/multi-worker
